2019-04-11 06:57:07,298 [Thread-7:123145513648128] [default:86] [ERROR]- 'dict' object has no attribute 'split'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/colleges/views.py", line 222, in post
    data["research"] = [i.uuid for i in Research.objects.filter(res_name__in=data.get('research').split(","))]
AttributeError: 'dict' object has no attribute 'split'
2019-04-11 06:57:35,702 [Thread-7:123145513648128] [default:86] [ERROR]- 'dict' object has no attribute 'split'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/colleges/views.py", line 222, in post
    data["research"] = [i.uuid for i in Research.objects.filter(res_name__in=data.get('research').split(","))]
AttributeError: 'dict' object has no attribute 'split'
2019-04-11 06:57:37,061 [Thread-7:123145513648128] [default:86] [ERROR]- 'dict' object has no attribute 'split'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/colleges/views.py", line 222, in post
    data["research"] = [i.uuid for i in Research.objects.filter(res_name__in=data.get('research').split(","))]
AttributeError: 'dict' object has no attribute 'split'
2019-04-11 08:09:16,068 [Thread-7:123145430065152] [default:86] [ERROR]- 'QuerySet' object has no attribute 'uuid'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 177, in put
    student_dict["academy"] = Academy.objects.filter(aca_cname=rowx[11]).uuid
AttributeError: 'QuerySet' object has no attribute 'uuid'
2019-04-11 08:36:23,017 [Thread-7:123145522167808] [default:86] [ERROR]- 'float' object has no attribute 'strip'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 164, in put
    rowx = list(map(lambda x: x.strip(), table.row_values(i)))
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 164, in <lambda>
    rowx = list(map(lambda x: x.strip(), table.row_values(i)))
AttributeError: 'float' object has no attribute 'strip'
2019-04-11 09:02:29,945 [Thread-7:123145438973952] [default:86] [ERROR]- list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 168, in put
    rowx[v] = v.strip()
TypeError: list indices must be integers or slices, not str
2019-04-11 09:57:47,883 [Thread-7:123145541447680] [default:86] [ERROR]- 'is_superusre' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 202, in put
    serializer.save()
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/serializers.py", line 54, in create
    user = User.objects.create(**user)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'is_superusre' is an invalid keyword argument for this function
2019-04-11 09:59:08,673 [Thread-7:123145596583936] [default:86] [ERROR]- 'stu_natioanlity' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 202, in put
    serializer.save()
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/serializers.py", line 55, in create
    new_tutor = Student.objects.create(user=user, academy=academy, major=major, tutor=tutor, **validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'stu_natioanlity' is an invalid keyword argument for this function
2019-04-11 10:00:59,647 [Thread-7:123145470152704] [default:86] [ERROR]- Cannot assign "{'username': 20193412333.0, 'first_name': '李', 'last_name': '斌', 'password': 'pbkdf2_sha256$120000$P4VbBAiKoJ5f$WnHaBzfb0JZ2AJztn3SVBI/QkzGGehiYlqONRtKT3gQ=', 'is_superuser': False, 'is_staff': True, 'is_active': False}": "Student.user" must be a "User" instance.
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 203, in put
    serializer.save()
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/serializers.py", line 55, in create
    new_tutor = Student.objects.create(user=user, academy=academy, major=major, tutor=tutor, **validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/base.py", line 467, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 210, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "{'username': 20193412333.0, 'first_name': '李', 'last_name': '斌', 'password': 'pbkdf2_sha256$120000$P4VbBAiKoJ5f$WnHaBzfb0JZ2AJztn3SVBI/QkzGGehiYlqONRtKT3gQ=', 'is_superuser': False, 'is_staff': True, 'is_active': False}": "Student.user" must be a "User" instance.
2019-04-11 11:18:23,843 [Thread-7:123145538772992] [default:86] [ERROR]- 'dict' object has no attribute 'first_name'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 203, in put
    serializer.save()
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/serializers.py", line 56, in create
    user = User.objects.filter(first_name=user.first_name)
AttributeError: 'dict' object has no attribute 'first_name'
2019-04-11 11:19:29,472 [Thread-7:123145581887488] [default:86] [ERROR]- Cannot assign "<QuerySet []>": "Student.user" must be a "User" instance.
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 203, in put
    serializer.save()
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 703, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/serializers.py", line 57, in create
    new_tutor = Student.objects.create(user=user, academy=academy, major=major, tutor=tutor, **validated_data)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/base.py", line 467, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 210, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<QuerySet []>": "Student.user" must be a "User" instance.
2019-04-11 12:37:49,343 [Thread-1:123145490878464] [default:86] [ERROR]- get() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
2019-04-11 12:39:06,919 [Thread-1:123145389150208] [default:86] [ERROR]- get() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
2019-04-11 12:39:08,347 [Thread-1:123145389150208] [default:86] [ERROR]- get() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
2019-04-11 12:45:57,175 [Thread-7:123145396801536] [default:86] [ERROR]- unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 221, in get
    aa = Student.objects.all().values('academy__aca_cname', 'major__maj_name').annotate(sum('academy__aca_cname'), sum(major__maj_name))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2019-04-11 12:46:02,601 [Thread-7:123145396801536] [default:86] [ERROR]- unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 221, in get
    aa = Student.objects.all().values('academy__aca_cname', 'major__maj_name').annotate(sum('academy__aca_cname'), sum(major__maj_name))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2019-04-11 12:46:04,010 [Thread-7:123145396801536] [default:86] [ERROR]- unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 221, in get
    aa = Student.objects.all().values('academy__aca_cname', 'major__maj_name').annotate(sum('academy__aca_cname'), sum(major__maj_name))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2019-04-11 12:46:24,995 [Thread-7:123145513017344] [default:86] [ERROR]- unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 221, in get
    aa = Student.objects.all().values('academy__aca_cname', 'major__maj_name').annotate(sum('academy__aca_cname'), sum('major__maj_name'))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2019-04-11 13:13:45,834 [Thread-7:123145489719296] [default:86] [ERROR]- 'maj_name'
Traceback (most recent call last):
  File "/Users/libin/Desktop/student_manage/Bistu/core/decorators/excepts.py", line 59, in handle_except
    return func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/libin/Desktop/student_manage/Bistu/apps/students/views.py", line 230, in get
    s_dict['major']['name'] = item['maj_name']
KeyError: 'maj_name'
